# Generated by Django 5.1.5 on 2025-01-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
